name: ece579
channels:
  - conda-forge
  - conda-forge/label/spyder_rc
  - conda-forge/label/spyder_dev
  - conda-forge/label/spyder_kernels_rc
dependencies:
  - _libavif_api=1.3.0=h57928b3_3
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aom=3.9.1=he0c23c2_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - audioread=3.0.1=py312h2e8e312_3
  - backports.zstd=1.3.0=py312h06d0912_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h78d62e6_4
  - cpython=3.12.12=py312hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.20=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.4.0=hac47afa_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.1=gpl_h21f70fe_911
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h05f76fc_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.44.5=h1f5b9c4_0
  - glslang=16.2.0=h294ba9c_1
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h5a1b470_0
  - hdf5=1.14.6=nompi_h89f0904_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=h1608b31_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.5=haf901d7_0
  - libavif16=1.3.0=ha08a409_3
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_2
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libflac=1.5.0=h08124e9_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hf3f85d1_8
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblapacke=3.11.0=5_h3ae206f_mkl
  - liblzma=5.8.2=hfd05255_0
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.13.0=qt6_py312h8547a2f_601
  - libopenvino=2025.4.1=h21f3657_1
  - libopenvino-auto-batch-plugin=2025.4.1=hd058e20_1
  - libopenvino-auto-plugin=2025.4.1=hd058e20_1
  - libopenvino-hetero-plugin=2025.4.1=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.4.1=h21f3657_1
  - libopenvino-intel-gpu-plugin=2025.4.1=h21f3657_1
  - libopenvino-ir-frontend=2025.4.1=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.4.1=hee3bb10_1
  - libopenvino-paddle-frontend=2025.4.1=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.4.1=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.4.1=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hac47afa_1
  - libopus=1.6.1=h6a83c73_0
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - librosa=0.11.0=pyhd8ed1ab_0
  - librsvg=2.60.0=hd5e4115_0
  - libsndfile=1.2.2=hc3b4fa0_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.46.0=py312hdb9728c_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_455
  - mpg123=1.32.9=h01009b0_0
  - msgpack-python=1.1.2=py312hf90b1b7_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.63.1=py312h560f1c9_0
  - numpy=2.2.5=py312h3150e54_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.13.0=qt6_py312h64de955_601
  - openexr=3.4.4=h3840fac_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.4=h24db6dd_0
  - openjph=0.26.0=hf13a347_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py312h95189c4_0
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.1.0=py312h31f0997_0
  - pip=26.0=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - playsound=1.3.0=pyhd8ed1ab_1
  - pooch=1.9.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py312he5662c2_0
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.13.0=qt6_py312h4c995e2_601
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py312h0c8bdd4_0
  - pysocks=1.7.1=pyh09c184e_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.12.12=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.2=h68b6638_4
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.8.0=np2py312hea30aaf_1
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.4.0=h5112557_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.10.2=pyh332efcf_0
  - shaderc=2025.5=h8fa7867_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - soxr=0.1.3=hcfcfb64_3
  - soxr-python=1.0.0=py312hbb81ca0_1
  - spirv-tools=2026.1=h49e36cd_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - standard-aifc=3.13.0=py312h2e8e312_3
  - standard-sunau=3.13.0=py312h2e8e312_3
  - statsmodels=0.14.6=py312h196c9fc_0
  - svt-av1=4.0.0=hac47afa_0
  - tbb=2022.3.0=h3155e25_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h6ed50ae_3
  - tornado=6.5.4=py312he06e257_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py312he06e257_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==2.4.0
      - astunparse==1.6.3
      - flatbuffers==25.12.19
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - keras==3.13.2
      - libclang==18.1.1
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - protobuf==6.33.5
      - rich==14.3.2
      - scipy==1.17.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - werkzeug==3.1.5
      - wrapt==2.1.1
prefix: C:\Users\JTWit\AppData\Local\spyder-6\envs\ece579
